export const dunyaUlkeIsimleri = [
  "Afganistan",
  "Almanya",
  "Amerikan Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antigua ve Barbuda",
  "Arjantin",
  "Arnavutluk",
  "Aruba",
  "Avustralya",
  "Avusturya",
  "Azerbaycan",
  "Bahamalar",
  "Bahreyn",
  "Bangladeş",
  "Barbados",
  "Batı Sahra",
  "Belçika",
  "Belize",
  "Benin",
  "Bermuda",
  "Beyaz Rusya",
  "Bhutan",
  "Birleşik Arap Emirlikleri",
  "Birleşik Krallık",
  "Bolivya",
  "Bonaire, Sint Eustatius ve Saba",
  "Bosna-Hersek",
  "Botsvana",
  "Brezilya",
  "Brunei",
  "Bulgaristan",
  "Burkina Faso",
  "Burundi",
  "Cape Verde",
  "Cebelitarık",
  "Cezayir",
  "Christmas Adası",
  "Cibuti",
  "Çad",
  "Çek Cumhuriyeti",
  "Çin",
  "Danimarka",
  "Dominika",
  "Dominik Cumhuriyeti",
  "Doğu Timor",
  "Ekvador",
  "Ekvator Ginesi",
  "El Salvador",
  "Endonezya",
  "Eritre",
  "Ermenistan",
  "Estonya",
  "Esvatini",
  "Etiyopya",
  "Fas",
  "Fiji",
  "Fildişi Sahili",
  "Filipinler",
  "Filistin",
  "Finlandiya",
  "Fransa",
  "Fransız Guyanası",
  "Fransız Güney ve Antarktika Toprakları",
  "Fransız Polinezyası",
  "Gabon",
  "Gambia",
  "Gana",
  "Gine",
  "Gine-Bissau",
  "Granada",
  "Grönland",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guyana",
  "Güney Afrika",
  "Güney Georgia ve Güney Sandwich Adaları",
  "Güney Kore",
  "Güney Sudan",
  "Gürcistan",
  "Haiti",
  "Hırvatistan",
  "Hollanda",
  "Hollanda Antilleri",
  "Honduras",
  "Hong Kong",
  "Irak",
  "İngiltere",
  "İran",
  "İrlanda",
  "İspanya",
  "İsrail",
  "İsveç",
  "İsviçre",
  "İtalya",
  "İzlanda",
  "Jamaika",
  "Japonya",
  "Jersey",
  "Kamboçya",
  "Kamerun",
  "Kanada",
  "Karadağ",
  "Katar",
  "Kazakistan",
  "Kenya",
  "Kırgızistan",
  "Kiribati",
  "Kolombiya",
  "Komorlar",
  "Kongo Demokratik Cumhuriyeti",
  "Kongo Cumhuriyeti",
  "Kosta Rika",
  "Kuveyt",
  "Kuzey Kore",
  "Kuzey Makedonya",
  "Küba",
  "Kuzey Mariana Adaları",
  "Laos",
  "Lesotho",
  "Letonya",
  "Liberya",
  "Libya",
  "Lihtenştayn",
  "Litvanya",
  "Lübnan",
  "Lüksemburg",
  "Macaristan",
  "Madagaskar",
  "Makao",
  "Malavi",
  "Maldivler",
  "Malezya",
  "Mali",
  "Malta",
  "Man Adası",
  "Marshall Adaları",
  "Martinik",
  "Mauritius",
  "Mayotte",
  "Meksika",
  "Mısır",
  "Mikronezya",
  "Moğolistan",
  "Moldova",
  "Monako",
  "Montserrat",
  "Moritanya",
  "Mozambik",
  "Myanmar",
  "Namibya",
  "Nauru",
  "Nepal",
  "Nijer",
  "Nijerya",
  "Nikaragua",
  "Niue",
  "Norfolk Adası",
  "Norveç",
  "Orta Afrika Cumhuriyeti",
  "Özbekistan",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua Yeni Gine",
  "Paraguay",
  "Peru",
  "Pitcairn Adaları",
  "Polonya",
  "Portekiz",
  "Porto Riko",
  "Reunion",
  "Romanya",
  "Ruanda",
  "Rusya",
  "Saint Barthelemy",
  "Saint Helena",
  "Saint Kitts ve Nevis",
  "Saint Lucia",
  "Saint Martin",
  "Saint Pierre ve Miquelon",
  "Saint Vincent ve Grenadinler",
  "Samoa",
  "San Marino",
  "Sao Tome ve Principe",
  "Senegal",
  "Seyşeller",
  "Sırbistan",
  "Sierra Leone",
  "Singapur",
  "Sint Maarten",
  "Slovakya",
  "Slovenya",
  "Solomon Adaları",
  "Somali",
  "Sri Lanka",
  "Sudan",
  "Surinam",
  "Suriye",
  "Suudi Arabistan",
  "Svalbard ve Jan Mayen",
  "Svaziland",
  "Şili",
  "Tacikistan",
  "Tanzanya",
  "Tayland",
  "Tayvan",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad ve Tobago",
  "Tunus",
  "Turks ve Caicos Adaları",
  "Tuvalu",
  "Türkiye",
  "Türkmenistan",
  "Uganda",
  "Ukrayna",
  "Umman",
  "Uruguay",
  "Ürdün",
  "Vanuatu",
  "Vatikan",
  "Venezuela",
  "Vietnam",
  "Wallis ve Futuna",
  "Yemen",
  "Yeni Kaledonya",
  "Yeni Zelanda",
  "Yeşil Burun Adaları",
  "Yunanistan",
  "Zambiya",
  "Zimbabve",
];
